services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - MODEL_PATH=/app/my_model3.h5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
